kcpKubeconfig: kcp-syncagent-kubeconfig
apiExportEndpointSliceName: certificates
hostAliases:
  enabled: true
  values:
    - ip: 10.96.2.2
      hostnames:
        - kcp.localhost
        - root.kcp.localhost
        - theseus.kcp.localhost
