apiVersion: apis.kcp.io/v1alpha2
kind: APIBinding
metadata:
  name: certificates
spec:
  reference:
    export:
      name: certificates
      path: root:provider
  permissionClaims:
  - resource: events
    verbs: ["*"]
    state: Accepted
    selector:
      matchAll: true
  - resource: secrets
    verbs: ["*"]
    state: Accepted
    selector:
      matchAll: true
  - resource: namespaces
    verbs: ["*"]
    state: Accepted
    selector:
      matchAll: true
