apiVersion: syncagent.kcp.io/v1alpha1
kind: PublishedResource
metadata:
  name: certificates
spec:
  resource:
    kind: Certificate
    apiGroup: cert-manager.io
    versions: [v1]
  projection:
    group: example.kcp.io
    kind: Certificate
    plural: certificates
    shortNames: [certs]
  related:
    - identifier: certificate
      origin: service
      group: ""
      version: v1
      resource: secrets
      object:
        reference:
          path: spec.secretName
