apiVersion: syncagent.kcp.io/v1alpha1
kind: PublishedResource
metadata:
  name: certificates
spec:
  resource:
    kind: Certificate
    apiGroup: example.kcp.io
    versions: [v1alpha1]
  related:
    - identifier: certificate
      origin: service
      group: ""
      version: v1
      resource: secrets
      object:
        reference:
          path: status.relatedResources.secret.name
